version: '3'
services:
  kanboard:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - .:/var/www/app:cached
     - kanboard_data:/var/www/app/data
     - kanboard_plugins:/var/www/app/plugins
     - kanboard_ssl:/etc/nginx/ssl
    environment:
      DATABASE_URL: mysql://kb:kb-secret@db/kanboard

  db:
    image: mariadb:latest
    expose:
      - "3306"
    ports:
      - "127.0.0.1:3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: kanboard
      MYSQL_USER: kb
      MYSQL_PASSWORD: kb-secret

volumes:
  kanboard_data:
    driver: local
  kanboard_plugins:
    driver: local
  kanboard_ssl:
    driver: local
